### ISSUE TITLE
Comprar novas escavadoras

### ISSUE THREAD

**Issue by jonathan-vieira** [joonathanvieira/sql-queys#2]
Precisamos comprar as novas escavadores para minerar a 2200 metros

**Comment by jonathan-vieira** [comment]
- [x] levantar requisitos da escavadeira
- [x] orçamentos com a Broken Rocket 
- [x] aquele choro pra conseguir um desconto
- [x] finalizar compra
